### PR TITLE
Pushing docker images as latest and version

### PR DESCRIPTION
**Pull request by naturalett**
Signed-off-by: Lidor Ettinger <lidor.ettinger@gmail.com>

**Description**

This PR fixes # 

**Notes to reviewers**

#### Checklist

- [] [Signed commits](https://github.com/layer5io/meshery/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin).
- [] PR title includes `[<name of area>]:<description>`

### CODE REVIEW

**Comment by kushthedude** [comment]
Just one question, is it nice to use make commands in ci.yml ? Shouldn't we keep the ci config simple from make file aliases?

**Comment by leecalcote** [comment]
Oh, I'm just seeing @kushthedude's question above.

**Comment by leecalcote** [comment]
At first blush, this seems like good code reuse. Perhaps, it's a fragile approach. Is that what you're alluding to @kushthedude?

**Comment by kushthedude** [comment]
> At first blush, this seems like good code reuse. Perhaps, it's a fragile approach. Is that what you're alluding to @kushthedude?

Yes

**Comment by naturalett** [comment]
Yes I agree. It makes sense.

**Pull request merged**
