### PR TITLE
image-hub README.md updated 

### LINKED ISSUE #62: [README] Need to fix Slack badge
**Description**

<a href="https://github.com/layer5io/image-hub/blob/master/README.md">README.md</a> is the first file one should read when starting a new project. For attractive look, we added some badges also.
But, there's a Slack badge failing, need to fix that. 
 
### Screenshot

**Current Behavior**

image

**Desired Behavior**
image

**Environment:**
 - OS: any [e.g. Ubuntu]
 - Browser: any [e.g. Chrome, Safari]
 - Version: any [e.g. 22]
 - Device: any [e.g. laptop, iPhone 8]

### PR DESCRIPTION
**Pull request by debjani1413**
Signed-off-by: debjani1413 <deydebjani916@gmail.com>

**Description**
The failing slack badge in README.md has been fixed.

This PR fixes #62  

**Notes to reviewers**

#### Checklist

- [x] [Signed commits](https://github.com/layer5io/meshery/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin).
- [x] PR title includes `[<name of area>]:<description>`

### CODE REVIEW

**Comment by amino19** [comment]
@debjani1413 : Almost done, just need to set pattern as : 
`[Slack](http://slack.layer5.io)`

or just use this line, a short edit! :slightly_smiling_face:

**Comment by debjani1413** [comment]
@amino19 you mean instead of this line :
<a href="http://slack.layer5.io" alt="Join Slack"></a>

I'll use this line right??
[Slack](http://slack.layer5.io)

**Comment by amino19** [comment]
@debjani1413 : Yes.

**Comment by debjani1413** [comment]
@amino19 I've done the required changes, do review !!

**Comment by amino19** [comment]
@debjani1413 : LGTM :partying_face: 

@alphaX86 : Pl take this to your end.

**Review by adithyaakrishna — APPROVED** [review]

**Comment by adithyaakrishna** [comment]
@amino19 Are there any other PRs in other repo similar to this? If so please do mention me there, I'll check and approve. After that I'll ask @Nikhil-Ladha to Merge it :)

**Comment by amino19** [comment]
@adithyaakrishna : Yes sure, we have more issues in other repo similar to this, that needs newcomer to fix!

**Review by Nikhil-Ladha — APPROVED** [review]

**Pull request merged**
