### PR TITLE
Fix: docker image fix

### PR DESCRIPTION
**Pull request by kanishkarj**
**Description**

There were some issues in the way in which the docker images were being built. I have fixed them here.

**Notes to reviewers**

#### Checklist

- [] [Signed commits](https://github.com/layer5io/meshery/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin).
- [] PR title includes `[<name of area>]:<description>`

### CODE REVIEW

**Comment by leecalcote** [comment]
@kanishkarj - a conflict in the makefile...

**Comment by kanishkarj** [comment]
I shall fix it righaway.

**Comment by kanishkarj** [comment]
Does that look good?

**Comment by leecalcote** [comment]
@kanishkarj fyi - https://github.com/layer5io/image-hub/runs/734518353#step:4:208

**Comment by kanishkarj** [comment]
Oh its a minor mistake I made while merging the PR. Shall fix it right away...

**Pull request merged**
