### PR TITLE
Updated old app logo to Image Hub logo

### LINKED ISSUE #7: [Web] Update old app logo to Image Hub logo
**Current Behavior**
[These logos](https://github.com/layer5io/image-hub/blob/master/web/src/assets/) are old.

**Desired Behavior**
The old logos need displaced with the Image Hub logo ([image-hub-logos.zip](https://github.com/layer5io/image-hub/files/4690925/image-hub-logos.zip)).

### PR DESCRIPTION
**Pull request by ashiscs**
fixes #7 
Signed-off-by: ashiscs <ashissingh640@gmail.com>

### CODE REVIEW

**Comment by leecalcote** [comment]
Thanks, @ashiscs. Can you post a screenshot to confirm that the image fits well?

**Comment by ashiscs** [comment]
Screenshot from 2020-07-04 00-07-50


> Thanks, @ashiscs. Can you post a screenshot to confirm that the image fits well?

Yes sir, image fits well !

**Comment by leecalcote** [comment]
@shivaylamba did we verify that this fits as expected in the app?

**Comment by leecalcote** [comment]
@shivaylamba, any word here? https://github.com/layer5io/image-hub/pull/27#issuecomment-653569633

**Comment by leecalcote** [comment]
@ashiscs @shivaylamba will either of you confirm that when this app is built that the new logo is of the right size?

**Pull request merged**
